# Generated by Django 4.0.4 on 2023-04-28 05:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=16)),
                ('version_name', models.CharField(default=None, max_length=256, null=True)),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=None, null=True, size=64)),
                ('players_online', models.IntegerField()),
                ('players_maximum', models.IntegerField()),
                ('recipient', models.CharField(default=None, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence1', models.SmallIntegerField()),
                ('sequence2', models.SmallIntegerField()),
                ('sequence3', models.SmallIntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('recipient', models.CharField(default=None, max_length=32, null=True)),
                ('assign_date', models.DateTimeField()),
            ],
        ),
    ]
